name: 🗄️ Back end
description: Solicite uma alteração ou correção no código do back end.
labels: ["enhancement", "triage", "backend"]

body:
  - type: markdown
    attributes:
      value: |
        - Evite descrições e títulos vagos como "Algo não está funcionando" ou "Alguns problemas" — seja o mais descritivo possível.
        - Issues devem conter informações suficientes para serem reproduzíveis. Se você tem dificuldades para reproduzir o problema, inicie uma [discussão](https://github.com/cacic-fct/fct-app/discussions/new).
        - Mantenha sua issue focada em um único problema. Se você tiver vários relatórios de bugs, crie uma issue separada para cada um deles.
        - Lembre-se de que o **FCT App** é um projeto de código aberto, que é mantido por voluntários. Se você puder, resolva o problema e envie um pull request.

        ___

  - type: textarea
    attributes:
      label: Descrição
      description: >
        Explicação clara e detalhada do pull request, incluindo qualquer informação adicional que você considere relevante, como imagens ou vídeos.
    validations:
      required: true


  - type: textarea
    attributes:
      label: Closes issues
      description: >
        Insira todas as issues que este pull request fecha.
      placeholder: |
        Closes #
        Closes #
        ...
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: Eu conferi se esta funcionalidade já foi solicitada antes
          required: true
        - label: Eu escrevi o título em inglês
          required: true
        - label: Eu escrevi a descrição em português
          required: true
        - label: O título e a descrição são suficientemente descritivos
          required: true
        - label: Meu pull request tem foco em um único recurso
          required: true
        - label: Não li nada do que está escrito e só selecionei tudo para enviar logo
          required: false
        - label: Entendo que recursos que tangenciam o propósito do projeto podem ser rejeitados
          required: true