.angular
.git
.github
.nx/cache
.nx/workspace-data
.vscode
coverage
dist
node_modules
tmp

.DS_Store
*.log
*.local

docker
import
certificate-templates
*.csv
*.sql

apps/*
!apps/public
!apps/public/**
!shared-angular
!shared-angular/**
!shared-data-types
!shared-data-types/**
!shared-utils
!shared-utils/**
