import { Component, inject, ViewEncapsulation } from '@angular/core';
import { ServiceWorkerService } from 'src/app/shared/services/service-worker/service-worker.service';
import { IonApp, IonRouterOutlet } from '@ionic/angular/standalone';
import { addIcons } from 'ionicons';
import {
  bookOutline,
  codeOutline,
  hammerOutline,
  warningOutline,
  refreshOutline,
  banOutline,
  serverOutline,
  play,
  logoFacebook,
  logoInstagram,
  logoLinkedin,
  logoTwitter,
  logoYoutube,
  mailOutline,
  globeOutline,
  callOutline,
  cash,
  paperPlane,
  pencil,
  ellipsisHorizontal,
  time,
  checkmark,
  person,
  shareSocialOutline,
  download,
  walletOutline,
  documentTextOutline,
  list,
  eye,
  settingsOutline,
  trashOutline,
  peopleOutline,
  listOutline,
  folderOpenOutline,
  add,
  close,
  qrCodeOutline,
  copy,
  folder,
  pin,
  sendOutline,
  flashOutline,
  cameraReverseOutline,
  arrowUp,
  arrowDown,
  pencilOutline,
  cashOutline,
  trash,
  chevronBack,
  chevronForward,
  mail,
  logoWhatsapp,
  sunny,
  cloudy,
  partlySunny,
  snow,
  rainy,
  thunderstorm,
  moon,
  calendar,
  albums,
  map,
  handRightOutline,
  menuOutline,
  filter,
  todayOutline,
  shareSocial,
  informationCircleOutline,
  calendarOutline,
  closeOutline,
  logInOutline,
  logOutOutline,
  personCircleOutline,
  albumsOutline,
  schoolOutline,
  peopleCircleOutline,
  buildOutline,
  search,
  closeCircleOutline,
  cloudUpload,
  checkmarkCircle,
  closeCircle,
  hourglass,
  cloudyNight,
  arrowForward,
  chevronDown,
  openOutline,
} from 'ionicons/icons';
import { PlausibleLocalService } from 'src/app/shared/services/plausible.service';
import { AuthService } from 'src/app/shared/services/auth.service';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.scss'],
  encapsulation: ViewEncapsulation.None,
  standalone: true,
  imports: [IonApp, IonRouterOutlet],
})
export class AppComponent {
  private plausibleLocal = inject(PlausibleLocalService);
  constructor(
    private swService: ServiceWorkerService,
    private authService: AuthService,
  ) {
    this.plausibleLocal.registerPlausible();

    // TODO: Não importar tudo em app.component.ts
    addIcons({
      bookOutline,
      codeOutline,
      hammerOutline,
      warningOutline,
      refreshOutline,
      banOutline,
      serverOutline,
      play,
      logoFacebook,
      logoInstagram,
      logoLinkedin,
      logoTwitter,
      logoYoutube,
      mailOutline,
      globeOutline,
      callOutline,
      cash,
      paperPlane,
      pencil,
      ellipsisHorizontal,
      time,
      checkmark,
      person,
      shareSocialOutline,
      download,
      walletOutline,
      documentTextOutline,
      list,
      eye,
      settingsOutline,
      trashOutline,
      peopleOutline,
      listOutline,
      folderOpenOutline,
      add,
      close,
      qrCodeOutline,
      copy,
      folder,
      pin,
      sendOutline,
      flashOutline,
      cameraReverseOutline,
      arrowUp,
      arrowDown,
      pencilOutline,
      cashOutline,
      trash,
      chevronBack,
      chevronForward,
      mail,
      logoWhatsapp,
      sunny,
      cloudy,
      partlySunny,
      snow,
      rainy,
      thunderstorm,
      moon,
      calendar,
      albums,
      map,
      handRightOutline,
      menuOutline,
      filter,
      todayOutline,
      shareSocial,
      informationCircleOutline,
      calendarOutline,
      closeOutline,
      logInOutline,
      logOutOutline,
      personCircleOutline,
      albumsOutline,
      schoolOutline,
      peopleCircleOutline,
      buildOutline,
      search,
      closeCircleOutline,
      cloudUpload,
      checkmarkCircle,
      closeCircle,
      hourglass,
      cloudyNight,
      arrowForward,
      chevronDown,
      openOutline,
    });
  }
}
