name: build

on:
  - workflow_call

      - name: Build for production
        run: bun run build --configuration=production
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build-artifacts
          path: dist/