name: ci

on:
  - workflow_call

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile