blank_issues_enabled: true
contact_links:
  - name: 📚 Documentação
    url: https://docs.fctapp.cacic.dev.br
    about: Encontre guias e explicações para perguntas frequentes.
  - name: 💬 Discussões
    url: https://github.com/cacic-fct/fct-app/discussions/new
    about: Pergunte e interaja com outros usuários.
