#!/usr/bin/env python3
"""
Import legacy secompp.sql data into the current PostgreSQL schema.

This importer only migrates relevant legacy entities:
- events -> major_events
- lectures + shortcourses -> events
- details + users -> people
- users_registered -> major_event_subscriptions
- users_registered_shortcourses -> event_subscriptions
- presence_lectures + presence_shortcourses -> event_attendances
- users_lectures + users_shortcourses -> event_lecturers

IDs generated by this importer are prefixed with: SYSCOMPP-1-
People IDs are generated as UUIDv7-style values.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

from legacy_sql_import_utils import (
    at_start_of_day,
    build_prefixed_id,
    coerce_text,
    decimal_to_int,
    deterministic_prefixed_id,
    normalize_cpf,
    normalize_email,
    normalize_person_name,
    parse_insert_rows_by_table,
    parse_mysql_date,
    strip_html,
    utc_now,
    uuid7_string,
)

PREFIX = "SYSCOMPP-1-"

REQUIRED_TABLES = {
    "details",
    "events",
    "lectures",
    "presence_lectures",
    "presence_shortcourses",
    "shortcourses",
    "users",
    "users_lectures",
    "users_registered",
    "users_registered_shortcourses",
    "users_shortcourses",
}


@dataclass(slots=True)
class MigrationPayload:
    major_events: list[dict[str, Any]]
    event_groups: list[dict[str, Any]]
    events: list[dict[str, Any]]
    people: list[dict[str, Any]]
    major_event_subscriptions: list[dict[str, Any]]
    event_subscriptions: list[dict[str, Any]]
    event_attendances: list[dict[str, Any]]
    event_lecturers: list[dict[str, Any]]
    skipped_major_subscriptions: int
    skipped_event_subscriptions: int
    skipped_attendances: int
    skipped_lecturers: int


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Import legacy secompp.sql data into PostgreSQL schema."
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("import/secompp.sql"),
        help="Path to secompp SQL dump file.",
    )
    parser.add_argument(
        "--database-url",
        type=str,
        default="",
        help="Full PostgreSQL URL. If omitted, individual --db-* options are used.",
    )
    parser.add_argument("--db-host", type=str, default="localhost")
    parser.add_argument("--db-port", type=int, default=5432)
    parser.add_argument("--db-name", type=str, default="postgres")
    parser.add_argument("--db-user", type=str, default="postgres")
    parser.add_argument("--db-password", type=str, default="postgres")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Build and report mapped rows without writing to database.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    payload = build_payload(args.input)

    print(
        "Prepared rows -> "
        f"major_events={len(payload.major_events)}, "
        f"event_groups={len(payload.event_groups)}, "
        f"events={len(payload.events)}, "
        f"people={len(payload.people)}, "
        f"major_event_subscriptions={len(payload.major_event_subscriptions)}, "
        f"event_subscriptions={len(payload.event_subscriptions)}, "
        f"event_attendances={len(payload.event_attendances)}, "
        f"event_lecturers={len(payload.event_lecturers)}, "
        f"skipped_major_subscriptions={payload.skipped_major_subscriptions}, "
        f"skipped_event_subscriptions={payload.skipped_event_subscriptions}, "
        f"skipped_attendances={payload.skipped_attendances}, "
        f"skipped_lecturers={payload.skipped_lecturers}"
    )

    if args.dry_run:
        print("Dry run enabled. No database changes were made.")
        return

    database_url = args.database_url or (
        f"postgresql://{args.db_user}:{args.db_password}@"
        f"{args.db_host}:{args.db_port}/{args.db_name}"
    )
    write_payload(database_url, payload)
    print("Import completed.")


def build_payload(sql_path: Path) -> MigrationPayload:
    parsed = parse_insert_rows_by_table(sql_path, REQUIRED_TABLES)
    now = utc_now()

    major_events, major_event_id_by_legacy, major_event_start_by_legacy = map_major_events(
        parsed["events"], now
    )

    lecture_seeds, shortcourse_seeds = map_event_seeds(
        parsed["lectures"],
        parsed["shortcourses"],
        major_event_id_by_legacy,
        major_event_start_by_legacy,
        now,
    )

    event_group_rows = build_event_groups(now)
    event_group_id_by_type = {row["type"]: row["id"] for row in event_group_rows}

    people_rows, user_id_to_person_id = map_people(parsed["details"], parsed["users"], now)

    (
        major_event_subscription_rows,
        skipped_major_subscriptions,
        paid_by_major_event,
    ) = map_major_event_subscriptions(
        parsed["users_registered"],
        user_id_to_person_id,
        major_event_id_by_legacy,
        major_event_start_by_legacy,
    )

    for row in major_events:
        if paid_by_major_event.get(row["id"], False):
            row["isPaymentRequired"] = True

    (
        event_subscription_rows,
        skipped_event_subscriptions,
    ) = map_event_subscriptions(
        parsed["users_registered_shortcourses"],
        user_id_to_person_id,
        shortcourse_seeds,
        now,
    )

    event_rows = build_event_rows(
        lecture_seeds,
        shortcourse_seeds,
        event_group_id_by_type,
        now,
    )

    (
        attendance_rows,
        skipped_attendances,
    ) = map_event_attendances(
        parsed["presence_lectures"],
        parsed["presence_shortcourses"],
        user_id_to_person_id,
        lecture_seeds,
        shortcourse_seeds,
        now,
    )

    (
        lecturer_rows,
        skipped_lecturers,
    ) = map_event_lecturers(
        parsed["users_lectures"],
        parsed["users_shortcourses"],
        user_id_to_person_id,
        lecture_seeds,
        shortcourse_seeds,
        now,
    )

    return MigrationPayload(
        major_events=major_events,
        event_groups=event_group_rows,
        events=event_rows,
        people=people_rows,
        major_event_subscriptions=major_event_subscription_rows,
        event_subscriptions=event_subscription_rows,
        event_attendances=attendance_rows,
        event_lecturers=lecturer_rows,
        skipped_major_subscriptions=skipped_major_subscriptions,
        skipped_event_subscriptions=skipped_event_subscriptions,
        skipped_attendances=skipped_attendances,
        skipped_lecturers=skipped_lecturers,
    )


def map_major_events(
    legacy_rows: list[dict[str, Any]],
    fallback_now: datetime,
) -> tuple[list[dict[str, Any]], dict[int, str], dict[int, datetime]]:
    rows: list[dict[str, Any]] = []
    id_by_legacy: dict[int, str] = {}
    start_by_legacy: dict[int, datetime] = {}

    for legacy_row in legacy_rows:
        legacy_id = decimal_to_int(legacy_row.get("idEvent"))
        if legacy_id is None:
            continue

        start_date = at_start_of_day(parse_mysql_date(legacy_row.get("start"))) or fallback_now
        end_date = at_start_of_day(parse_mysql_date(legacy_row.get("end"))) or start_date
        if end_date < start_date:
            end_date = start_date

        location = coerce_text(legacy_row.get("location"), fix_mojibake=True)
        link = coerce_text(legacy_row.get("link"), fix_mojibake=True)
        description = coerce_text(legacy_row.get("description"), fix_mojibake=True)

        description_parts = [part for part in [description] if part]
        if location:
            description_parts.append(f"Local: {location}")
        if link:
            description_parts.append(f"Link legado: {link}")

        major_event_id = build_prefixed_id(PREFIX, "major-event", legacy_id)
        id_by_legacy[legacy_id] = major_event_id
        start_by_legacy[legacy_id] = start_date

        rows.append(
            {
                "id": major_event_id,
                "name": coerce_text(legacy_row.get("name"), fix_mojibake=True)
                or f"Evento legado {legacy_id}",
                "startDate": start_date,
                "endDate": end_date,
                "description": "\n".join(description_parts) if description_parts else None,
                "isPaymentRequired": False,
                "createdAt": start_date,
                "updatedAt": fallback_now,
            }
        )

    return rows, id_by_legacy, start_by_legacy


def map_event_seeds(
    lecture_rows: list[dict[str, Any]],
    shortcourse_rows: list[dict[str, Any]],
    major_event_id_by_legacy: dict[int, str],
    major_event_start_by_legacy: dict[int, datetime],
    fallback_now: datetime,
) -> tuple[dict[int, dict[str, Any]], dict[int, dict[str, Any]]]:
    lecture_seeds: dict[int, dict[str, Any]] = {}
    shortcourse_seeds: dict[int, dict[str, Any]] = {}

    for row in lecture_rows:
        legacy_lecture_id = decimal_to_int(row.get("idLecture"))
        legacy_event_id = decimal_to_int(row.get("idEventFK"))
        if legacy_lecture_id is None or legacy_event_id is None:
            continue
        major_event_id = major_event_id_by_legacy.get(legacy_event_id)
        if major_event_id is None:
            continue
        start_date = major_event_start_by_legacy.get(legacy_event_id, fallback_now)
        lecture_seeds[legacy_lecture_id] = {
            "id": build_prefixed_id(PREFIX, "event", "lecture", legacy_lecture_id),
            "name": coerce_text(row.get("name"), fix_mojibake=True)
            or f"Palestra {legacy_lecture_id}",
            "type": "PALESTRA",
            "emoji": "🎤",
            "description": coerce_text(row.get("description"), fix_mojibake=True),
            "shortDescription": strip_html(row.get("description")),
            "creditMinutes": None,
            "startDate": start_date,
            "endDate": start_date,
            "locationDescription": None,
            "majorEventId": major_event_id,
            "slots": None,
            "createdAt": start_date,
        }

    for row in shortcourse_rows:
        legacy_shortcourse_id = decimal_to_int(row.get("idShortcourse"))
        legacy_event_id = decimal_to_int(row.get("idEventFK"))
        if legacy_shortcourse_id is None or legacy_event_id is None:
            continue
        major_event_id = major_event_id_by_legacy.get(legacy_event_id)
        if major_event_id is None:
            continue
        start_date = major_event_start_by_legacy.get(legacy_event_id, fallback_now)
        workload_hours = decimal_to_int(row.get("workload"))
        shortcourse_seeds[legacy_shortcourse_id] = {
            "id": build_prefixed_id(PREFIX, "event", "shortcourse", legacy_shortcourse_id),
            "name": coerce_text(row.get("name"), fix_mojibake=True)
            or f"Minicurso {legacy_shortcourse_id}",
            "type": "MINICURSO",
            "emoji": "🧪",
            "description": coerce_text(row.get("description"), fix_mojibake=True),
            "shortDescription": strip_html(row.get("description")),
            "creditMinutes": (workload_hours * 60) if workload_hours is not None else None,
            "startDate": start_date,
            "endDate": start_date,
            "locationDescription": None,
            "majorEventId": major_event_id,
            "slots": decimal_to_int(row.get("vacancies")),
            "createdAt": start_date,
        }

    return lecture_seeds, shortcourse_seeds


def build_event_groups(now: datetime) -> list[dict[str, Any]]:
    return [
        {
            "id": build_prefixed_id(PREFIX, "event-group", "palestras"),
            "name": "Palestras (SECOMPP legado 1)",
            "type": "PALESTRA",
            "createdAt": now,
            "updatedAt": now,
        },
        {
            "id": build_prefixed_id(PREFIX, "event-group", "minicursos"),
            "name": "Minicursos (SECOMPP legado 1)",
            "type": "MINICURSO",
            "createdAt": now,
            "updatedAt": now,
        },
    ]


def map_people(
    detail_rows: list[dict[str, Any]],
    user_rows: list[dict[str, Any]],
    fallback_now: datetime,
) -> tuple[list[dict[str, Any]], dict[int, str]]:
    person_by_key: dict[str, dict[str, Any]] = {}
    detail_id_to_person_id: dict[int, str] = {}
    user_id_to_person_id: dict[int, str] = {}

    for detail_row in detail_rows:
        detail_id = decimal_to_int(detail_row.get("idDetail"))
        if detail_id is None:
            continue
        cpf = normalize_cpf(detail_row.get("cpf"))
        person_key = f"cpf:{cpf}" if cpf else f"detail:{detail_id}"
        person_id = uuid7_string()

        existing = person_by_key.get(person_key)
        if existing is None:
            person_by_key[person_key] = {
                "id": person_id,
                "name": normalize_person_name(detail_row.get("name")) or f"Pessoa {detail_id}",
                "email": None,
                "identityDocument": cpf,
                "academicId": None,
                "externalRef": build_prefixed_id(PREFIX, "legacy-detail", detail_id),
                "createdAt": fallback_now,
                "updatedAt": fallback_now,
            }
        else:
            if existing.get("identityDocument") is None and cpf is not None:
                existing["identityDocument"] = cpf

        detail_id_to_person_id[detail_id] = person_by_key[person_key]["id"]

    for user_row in user_rows:
        user_id = decimal_to_int(user_row.get("idUser"))
        detail_id = decimal_to_int(user_row.get("idDetailFK"))
        if user_id is None:
            continue

        person_id = detail_id_to_person_id.get(detail_id or -1)
        if person_id is None:
            person_id = uuid7_string()
            person_key = f"user:{user_id}"
            person_by_key[person_key] = {
                "id": person_id,
                "name": f"Pessoa {user_id}",
                "email": None,
                "identityDocument": None,
                "academicId": None,
                "externalRef": build_prefixed_id(PREFIX, "legacy-user", user_id),
                "createdAt": fallback_now,
                "updatedAt": fallback_now,
            }
        else:
            person_key = next(
                (candidate for candidate, row in person_by_key.items() if row["id"] == person_id),
                "",
            )

        email = normalize_email(user_row.get("email"))
        if person_key and email:
            if person_by_key[person_key].get("email") is None:
                person_by_key[person_key]["email"] = email

        user_id_to_person_id[user_id] = person_id

    people = sorted(person_by_key.values(), key=lambda row: row["id"])
    return people, user_id_to_person_id


def map_major_event_subscriptions(
    legacy_rows: list[dict[str, Any]],
    user_id_to_person_id: dict[int, str],
    major_event_id_by_legacy: dict[int, str],
    major_event_start_by_legacy: dict[int, datetime],
) -> tuple[list[dict[str, Any]], int, dict[str, bool]]:
    rows_by_id: dict[str, dict[str, Any]] = {}
    skipped = 0
    paid_by_major_event: dict[str, bool] = {}

    for row in legacy_rows:
        user_id = decimal_to_int(row.get("idUserFK"))
        legacy_event_id = decimal_to_int(row.get("idEventFK"))
        if user_id is None or legacy_event_id is None:
            skipped += 1
            continue
        person_id = user_id_to_person_id.get(user_id)
        major_event_id = major_event_id_by_legacy.get(legacy_event_id)
        if person_id is None or major_event_id is None:
            skipped += 1
            continue

        amount_paid = decimal_to_int(row.get("amount"))
        if amount_paid is not None and amount_paid > 0:
            paid_by_major_event[major_event_id] = True

        status_raw = (coerce_text(row.get("status")) or "").upper()
        subscription_status = "CONFIRMED" if status_raw == "S" else "WAITING_RECEIPT_UPLOAD"

        subscription_id = deterministic_prefixed_id(
            PREFIX, f"legacy1-major-sub:{user_id}:{legacy_event_id}"
        )
        rows_by_id[subscription_id] = {
            "id": subscription_id,
            "majorEventId": major_event_id,
            "personId": person_id,
            "amountPaid": amount_paid,
            "paymentDate": None,
            "paymentTier": None,
            "subscriptionStatus": subscription_status,
            "createdAt": major_event_start_by_legacy.get(legacy_event_id, utc_now()),
            "createdById": None,
        }

    return sorted(rows_by_id.values(), key=lambda item: item["id"]), skipped, paid_by_major_event


def map_event_subscriptions(
    legacy_rows: list[dict[str, Any]],
    user_id_to_person_id: dict[int, str],
    shortcourse_seeds: dict[int, dict[str, Any]],
    fallback_now: datetime,
) -> tuple[list[dict[str, Any]], int]:
    rows_by_id: dict[str, dict[str, Any]] = {}
    skipped = 0

    for row in legacy_rows:
        user_id = decimal_to_int(row.get("idUserFK"))
        shortcourse_id = decimal_to_int(row.get("idShortcourseFK"))
        if user_id is None or shortcourse_id is None:
            skipped += 1
            continue
        person_id = user_id_to_person_id.get(user_id)
        event_seed = shortcourse_seeds.get(shortcourse_id)
        if person_id is None or event_seed is None:
            skipped += 1
            continue

        subscription_id = deterministic_prefixed_id(
            PREFIX, f"legacy1-event-sub:shortcourse:{user_id}:{shortcourse_id}"
        )
        rows_by_id[subscription_id] = {
            "id": subscription_id,
            "eventId": event_seed["id"],
            "personId": person_id,
            "createdAt": event_seed.get("startDate") or fallback_now,
            "createdById": None,
        }

    return sorted(rows_by_id.values(), key=lambda item: item["id"]), skipped


def build_event_rows(
    lecture_seeds: dict[int, dict[str, Any]],
    shortcourse_seeds: dict[int, dict[str, Any]],
    event_group_id_by_type: dict[str, str],
    fallback_now: datetime,
) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for seed in [*lecture_seeds.values(), *shortcourse_seeds.values()]:
        rows.append(
            {
                "id": seed["id"],
                "name": seed["name"],
                "creditMinutes": seed["creditMinutes"],
                "startDate": seed["startDate"],
                "endDate": seed["endDate"],
                "type": seed["type"],
                "emoji": seed["emoji"],
                "description": seed["description"],
                "shortDescription": seed["shortDescription"],
                "latitude": None,
                "longitude": None,
                "locationDescription": seed["locationDescription"],
                "majorEventId": seed["majorEventId"],
                "eventGroupId": event_group_id_by_type.get(seed["type"]),
                "allowSubscription": True,
                "slots": seed["slots"],
                "shouldIssueCertificate": False,
                "shouldCollectAttendance": True,
                "isOnlineAttendanceAllowed": False,
                "onlineAttendanceCode": None,
                "onlineAttendanceStartDate": None,
                "onlineAttendanceEndDate": None,
                "publiclyVisible": True,
                "youtubeCode": None,
                "buttonText": None,
                "buttonLink": None,
                "createdAt": seed.get("createdAt") or fallback_now,
                "createdById": None,
                "updatedAt": fallback_now,
            }
        )

    return sorted(rows, key=lambda item: item["id"])


def map_event_attendances(
    lecture_rows: list[dict[str, Any]],
    shortcourse_rows: list[dict[str, Any]],
    user_id_to_person_id: dict[int, str],
    lecture_seeds: dict[int, dict[str, Any]],
    shortcourse_seeds: dict[int, dict[str, Any]],
    fallback_now: datetime,
) -> tuple[list[dict[str, Any]], int]:
    rows_by_pair: dict[tuple[str, str], dict[str, Any]] = {}
    skipped = 0

    for row in lecture_rows:
        user_id = decimal_to_int(row.get("idUserFK"))
        lecture_id = decimal_to_int(row.get("idLectureFK"))
        if user_id is None or lecture_id is None:
            skipped += 1
            continue
        person_id = user_id_to_person_id.get(user_id)
        event_seed = lecture_seeds.get(lecture_id)
        if person_id is None or event_seed is None:
            skipped += 1
            continue
        pair = (person_id, event_seed["id"])
        rows_by_pair[pair] = {
            "personId": pair[0],
            "eventId": pair[1],
            "attendedAt": event_seed.get("startDate") or fallback_now,
            "createdAt": event_seed.get("startDate") or fallback_now,
            "createdById": None,
        }

    for row in shortcourse_rows:
        user_id = decimal_to_int(row.get("idUserFK"))
        shortcourse_id = decimal_to_int(row.get("idShortcourseFK"))
        if user_id is None or shortcourse_id is None:
            skipped += 1
            continue
        person_id = user_id_to_person_id.get(user_id)
        event_seed = shortcourse_seeds.get(shortcourse_id)
        if person_id is None or event_seed is None:
            skipped += 1
            continue
        pair = (person_id, event_seed["id"])
        rows_by_pair[pair] = {
            "personId": pair[0],
            "eventId": pair[1],
            "attendedAt": event_seed.get("startDate") or fallback_now,
            "createdAt": event_seed.get("startDate") or fallback_now,
            "createdById": None,
        }

    rows = [rows_by_pair[key] for key in sorted(rows_by_pair)]
    return rows, skipped


def map_event_lecturers(
    lecture_rows: list[dict[str, Any]],
    shortcourse_rows: list[dict[str, Any]],
    user_id_to_person_id: dict[int, str],
    lecture_seeds: dict[int, dict[str, Any]],
    shortcourse_seeds: dict[int, dict[str, Any]],
    fallback_now: datetime,
) -> tuple[list[dict[str, Any]], int]:
    rows_by_pair: dict[tuple[str, str], dict[str, Any]] = {}
    skipped = 0

    for row in lecture_rows:
        user_id = decimal_to_int(row.get("idUserFK"))
        lecture_id = decimal_to_int(row.get("idLectureFK"))
        if user_id is None or lecture_id is None:
            skipped += 1
            continue
        person_id = user_id_to_person_id.get(user_id)
        event_seed = lecture_seeds.get(lecture_id)
        if person_id is None or event_seed is None:
            skipped += 1
            continue
        pair = (event_seed["id"], person_id)
        rows_by_pair[pair] = {
            "eventId": pair[0],
            "personId": pair[1],
            "createdAt": event_seed.get("startDate") or fallback_now,
            "createdById": None,
        }

    for row in shortcourse_rows:
        user_id = decimal_to_int(row.get("idUserFK"))
        shortcourse_id = decimal_to_int(row.get("idShortcourseFK"))
        if user_id is None or shortcourse_id is None:
            skipped += 1
            continue
        person_id = user_id_to_person_id.get(user_id)
        event_seed = shortcourse_seeds.get(shortcourse_id)
        if person_id is None or event_seed is None:
            skipped += 1
            continue
        pair = (event_seed["id"], person_id)
        rows_by_pair[pair] = {
            "eventId": pair[0],
            "personId": pair[1],
            "createdAt": event_seed.get("startDate") or fallback_now,
            "createdById": None,
        }

    rows = [rows_by_pair[key] for key in sorted(rows_by_pair)]
    return rows, skipped


def write_payload(database_url: str, payload: MigrationPayload) -> None:
    try:
        import psycopg
    except ImportError as error:
        raise RuntimeError(
            "Missing dependency 'psycopg'. Install with: pip install \"psycopg[binary]\""
        ) from error

    with psycopg.connect(database_url) as connection:
        with connection.cursor() as cursor:
            old_person_id_to_external_ref, resolved_person_id_by_external_ref = (
                reconcile_people_ids_with_database(cursor, payload.people)
            )
            rebind_people_foreign_keys(
                payload,
                old_person_id_to_external_ref,
                resolved_person_id_by_external_ref,
            )

            execute_many_if_any(
                cursor,
                """
                INSERT INTO major_events (
                  id, name, "startDate", "endDate", description, "isPaymentRequired", "createdAt", "updatedAt"
                )
                VALUES (
                  %(id)s, %(name)s, %(startDate)s, %(endDate)s, %(description)s, %(isPaymentRequired)s, %(createdAt)s, %(updatedAt)s
                )
                ON CONFLICT (id) DO UPDATE SET
                  name = EXCLUDED.name,
                  "startDate" = EXCLUDED."startDate",
                  "endDate" = EXCLUDED."endDate",
                  description = EXCLUDED.description,
                  "isPaymentRequired" = EXCLUDED."isPaymentRequired",
                  "updatedAt" = EXCLUDED."updatedAt"
                """,
                payload.major_events,
            )

            event_groups = [
                {
                    "id": row["id"],
                    "name": row["name"],
                    "createdAt": row["createdAt"],
                    "updatedAt": row["updatedAt"],
                }
                for row in payload.event_groups
            ]
            execute_many_if_any(
                cursor,
                """
                INSERT INTO event_groups (
                  id, name, "createdAt", "updatedAt"
                )
                VALUES (
                  %(id)s, %(name)s, %(createdAt)s, %(updatedAt)s
                )
                ON CONFLICT (id) DO UPDATE SET
                  name = EXCLUDED.name,
                  "updatedAt" = EXCLUDED."updatedAt"
                """,
                event_groups,
            )

            execute_many_if_any(
                cursor,
                """
                INSERT INTO events (
                  id, name, "creditMinutes", "startDate", "endDate", type, emoji,
                  description, "shortDescription", latitude, longitude, "locationDescription",
                  "majorEventId", "eventGroupId", "allowSubscription", slots,
                  "shouldIssueCertificate", "shouldCollectAttendance",
                  "isOnlineAttendanceAllowed", "onlineAttendanceCode",
                  "onlineAttendanceStartDate", "onlineAttendanceEndDate",
                  "publiclyVisible", "youtubeCode", "buttonText", "buttonLink",
                  "createdAt", "createdById", "updatedAt"
                )
                VALUES (
                  %(id)s, %(name)s, %(creditMinutes)s, %(startDate)s, %(endDate)s, %(type)s, %(emoji)s,
                  %(description)s, %(shortDescription)s, %(latitude)s, %(longitude)s, %(locationDescription)s,
                  %(majorEventId)s, %(eventGroupId)s, %(allowSubscription)s, %(slots)s,
                  %(shouldIssueCertificate)s, %(shouldCollectAttendance)s,
                  %(isOnlineAttendanceAllowed)s, %(onlineAttendanceCode)s,
                  %(onlineAttendanceStartDate)s, %(onlineAttendanceEndDate)s,
                  %(publiclyVisible)s, %(youtubeCode)s, %(buttonText)s, %(buttonLink)s,
                  %(createdAt)s, %(createdById)s, %(updatedAt)s
                )
                ON CONFLICT (id) DO UPDATE SET
                  name = EXCLUDED.name,
                  "creditMinutes" = EXCLUDED."creditMinutes",
                  "startDate" = EXCLUDED."startDate",
                  "endDate" = EXCLUDED."endDate",
                  type = EXCLUDED.type,
                  emoji = EXCLUDED.emoji,
                  description = EXCLUDED.description,
                  "shortDescription" = EXCLUDED."shortDescription",
                  latitude = EXCLUDED.latitude,
                  longitude = EXCLUDED.longitude,
                  "locationDescription" = EXCLUDED."locationDescription",
                  "majorEventId" = EXCLUDED."majorEventId",
                  "eventGroupId" = EXCLUDED."eventGroupId",
                  "allowSubscription" = EXCLUDED."allowSubscription",
                  slots = EXCLUDED.slots,
                  "shouldIssueCertificate" = EXCLUDED."shouldIssueCertificate",
                  "shouldCollectAttendance" = EXCLUDED."shouldCollectAttendance",
                  "isOnlineAttendanceAllowed" = EXCLUDED."isOnlineAttendanceAllowed",
                  "onlineAttendanceCode" = EXCLUDED."onlineAttendanceCode",
                  "onlineAttendanceStartDate" = EXCLUDED."onlineAttendanceStartDate",
                  "onlineAttendanceEndDate" = EXCLUDED."onlineAttendanceEndDate",
                  "publiclyVisible" = EXCLUDED."publiclyVisible",
                  "youtubeCode" = EXCLUDED."youtubeCode",
                  "buttonText" = EXCLUDED."buttonText",
                  "buttonLink" = EXCLUDED."buttonLink",
                  "updatedAt" = EXCLUDED."updatedAt"
                """,
                payload.events,
            )

            execute_many_if_any(
                cursor,
                """
                INSERT INTO people (
                  id, name, email, "identityDocument", "academicId", "externalRef", "createdAt", "updatedAt"
                )
                VALUES (
                  %(id)s, %(name)s, %(email)s, %(identityDocument)s, %(academicId)s, %(externalRef)s, %(createdAt)s, %(updatedAt)s
                )
                ON CONFLICT ("externalRef") DO UPDATE SET
                  name = EXCLUDED.name,
                  email = EXCLUDED.email,
                  "identityDocument" = EXCLUDED."identityDocument",
                  "academicId" = EXCLUDED."academicId",
                  "updatedAt" = EXCLUDED."updatedAt"
                """,
                payload.people,
            )

            execute_many_if_any(
                cursor,
                """
                INSERT INTO major_event_subscriptions (
                  id, "majorEventId", "personId", "amountPaid", "paymentDate",
                  "paymentTier", "subscriptionStatus", "createdAt", "createdById"
                )
                VALUES (
                  %(id)s, %(majorEventId)s, %(personId)s, %(amountPaid)s, %(paymentDate)s,
                  %(paymentTier)s, %(subscriptionStatus)s, %(createdAt)s, %(createdById)s
                )
                ON CONFLICT (id) DO UPDATE SET
                  "majorEventId" = EXCLUDED."majorEventId",
                  "personId" = EXCLUDED."personId",
                  "amountPaid" = EXCLUDED."amountPaid",
                  "paymentDate" = EXCLUDED."paymentDate",
                  "paymentTier" = EXCLUDED."paymentTier",
                  "subscriptionStatus" = EXCLUDED."subscriptionStatus",
                  "createdAt" = EXCLUDED."createdAt",
                  "createdById" = EXCLUDED."createdById"
                """,
                payload.major_event_subscriptions,
            )

            execute_many_if_any(
                cursor,
                """
                INSERT INTO event_subscriptions (
                  id, "eventId", "personId", "createdAt", "createdById"
                )
                VALUES (
                  %(id)s, %(eventId)s, %(personId)s, %(createdAt)s, %(createdById)s
                )
                ON CONFLICT (id) DO UPDATE SET
                  "eventId" = EXCLUDED."eventId",
                  "personId" = EXCLUDED."personId",
                  "createdAt" = EXCLUDED."createdAt",
                  "createdById" = EXCLUDED."createdById"
                """,
                payload.event_subscriptions,
            )

            execute_many_if_any(
                cursor,
                """
                INSERT INTO event_attendances (
                  "personId", "eventId", "attendedAt", "createdAt", "createdById"
                )
                VALUES (
                  %(personId)s, %(eventId)s, %(attendedAt)s, %(createdAt)s, %(createdById)s
                )
                ON CONFLICT ("personId", "eventId") DO UPDATE SET
                  "attendedAt" = EXCLUDED."attendedAt",
                  "createdAt" = EXCLUDED."createdAt",
                  "createdById" = EXCLUDED."createdById"
                """,
                payload.event_attendances,
            )

            execute_many_if_any(
                cursor,
                """
                INSERT INTO event_lecturers (
                  "eventId", "personId", "createdAt", "createdById"
                )
                VALUES (
                  %(eventId)s, %(personId)s, %(createdAt)s, %(createdById)s
                )
                ON CONFLICT ("eventId", "personId") DO UPDATE SET
                  "createdAt" = EXCLUDED."createdAt",
                  "createdById" = EXCLUDED."createdById"
                """,
                payload.event_lecturers,
            )


def reconcile_people_ids_with_database(
    cursor: Any, people_rows: list[dict[str, Any]]
) -> tuple[dict[str, str], dict[str, str]]:
    old_person_id_to_external_ref: dict[str, str] = {
        row["id"]: row["externalRef"] for row in people_rows
    }
    resolved_person_id_by_external_ref: dict[str, str] = {
        row["externalRef"]: row["id"] for row in people_rows
    }

    external_refs = list(resolved_person_id_by_external_ref.keys())
    if external_refs:
        cursor.execute(
            'SELECT id, "externalRef" FROM people WHERE "externalRef" = ANY(%s)',
            (external_refs,),
        )
        for person_id, external_ref in cursor.fetchall():
            resolved_person_id_by_external_ref[str(external_ref)] = str(person_id)

    for row in people_rows:
        row["id"] = resolved_person_id_by_external_ref[row["externalRef"]]

    return old_person_id_to_external_ref, resolved_person_id_by_external_ref


def rebind_people_foreign_keys(
    payload: MigrationPayload,
    old_person_id_to_external_ref: dict[str, str],
    resolved_person_id_by_external_ref: dict[str, str],
) -> None:
    collections_and_keys = (
        (payload.major_event_subscriptions, "personId"),
        (payload.event_subscriptions, "personId"),
        (payload.event_attendances, "personId"),
        (payload.event_lecturers, "personId"),
    )

    for rows, key in collections_and_keys:
        for row in rows:
            old_person_id = row.get(key)
            if not isinstance(old_person_id, str):
                raise RuntimeError("Unexpected personId type while rebinding references.")
            external_ref = old_person_id_to_external_ref.get(old_person_id)
            if external_ref is None:
                raise RuntimeError(f"Missing externalRef mapping for personId '{old_person_id}'.")
            resolved_person_id = resolved_person_id_by_external_ref.get(external_ref)
            if resolved_person_id is None:
                raise RuntimeError(
                    f"Missing resolved personId for externalRef '{external_ref}'."
                )
            row[key] = resolved_person_id


def execute_many_if_any(cursor: Any, query: str, rows: list[dict[str, Any]]) -> None:
    if not rows:
        return
    cursor.executemany(query, rows)


if __name__ == "__main__":
    main()
