#!/usr/bin/env python3
"""
Import legacy secompp2.sql data into the current PostgreSQL schema.

This importer only migrates relevant legacy entities:
- ano_referencia -> major_events
- minicurso + palestra -> events
- dados -> people
- inscricao -> major_event_subscriptions
- participacao_minicurso + participacao_palestra -> event_subscriptions
- participacao_minicurso(presenca=1) -> event_attendances
- ministrante_minicurso + palestra.CPFusuarioFK -> event_lecturers

IDs generated by this importer are prefixed with: SYSCOMP-2-
People IDs are generated as UUIDv7-style values.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from datetime import date, datetime
from pathlib import Path
from typing import Any

from legacy_sql_import_utils import (
    at_start_of_day,
    build_prefixed_id,
    coerce_text,
    combine_date_and_time,
    decimal_to_int,
    deterministic_prefixed_id,
    normalize_cpf,
    normalize_email,
    normalize_person_name,
    parse_insert_rows_by_table,
    parse_mysql_date,
    parse_mysql_datetime,
    parse_mysql_time,
    strip_html,
    utc_now,
    uuid7_string,
)

PREFIX = "SYSCOMP-2-"

REQUIRED_TABLES = {
    "ano_referencia",
    "dados",
    "inscricao",
    "minicurso",
    "ministrante_minicurso",
    "palestra",
    "participacao_minicurso",
    "participacao_palestra",
}


@dataclass(slots=True)
class MigrationPayload:
    major_events: list[dict[str, Any]]
    event_groups: list[dict[str, Any]]
    events: list[dict[str, Any]]
    people: list[dict[str, Any]]
    major_event_subscriptions: list[dict[str, Any]]
    event_subscriptions: list[dict[str, Any]]
    event_attendances: list[dict[str, Any]]
    event_lecturers: list[dict[str, Any]]
    skipped_major_subscriptions: int
    skipped_event_subscriptions: int
    skipped_attendances: int
    skipped_lecturers: int


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Import legacy secompp2.sql data into PostgreSQL schema."
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("import/secompp2.sql"),
        help="Path to secompp2 SQL dump file.",
    )
    parser.add_argument(
        "--database-url",
        type=str,
        default="",
        help="Full PostgreSQL URL. If omitted, individual --db-* options are used.",
    )
    parser.add_argument("--db-host", type=str, default="localhost")
    parser.add_argument("--db-port", type=int, default=5432)
    parser.add_argument("--db-name", type=str, default="postgres")
    parser.add_argument("--db-user", type=str, default="postgres")
    parser.add_argument("--db-password", type=str, default="postgres")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Build and report mapped rows without writing to database.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    payload = build_payload(args.input)

    print(
        "Prepared rows -> "
        f"major_events={len(payload.major_events)}, "
        f"event_groups={len(payload.event_groups)}, "
        f"events={len(payload.events)}, "
        f"people={len(payload.people)}, "
        f"major_event_subscriptions={len(payload.major_event_subscriptions)}, "
        f"event_subscriptions={len(payload.event_subscriptions)}, "
        f"event_attendances={len(payload.event_attendances)}, "
        f"event_lecturers={len(payload.event_lecturers)}, "
        f"skipped_major_subscriptions={payload.skipped_major_subscriptions}, "
        f"skipped_event_subscriptions={payload.skipped_event_subscriptions}, "
        f"skipped_attendances={payload.skipped_attendances}, "
        f"skipped_lecturers={payload.skipped_lecturers}"
    )

    if args.dry_run:
        print("Dry run enabled. No database changes were made.")
        return

    database_url = args.database_url or (
        f"postgresql://{args.db_user}:{args.db_password}@"
        f"{args.db_host}:{args.db_port}/{args.db_name}"
    )
    write_payload(database_url, payload)
    print("Import completed.")


def build_payload(sql_path: Path) -> MigrationPayload:
    parsed = parse_insert_rows_by_table(sql_path, REQUIRED_TABLES)
    now = utc_now()

    major_event_id_by_year_ref = map_major_event_ids(parsed["ano_referencia"])
    event_group_rows = build_event_groups(now)
    event_group_id_by_type = {row["type"]: row["id"] for row in event_group_rows}

    minicurso_seeds = map_minicursos(parsed["minicurso"], major_event_id_by_year_ref, now)
    palestra_seeds = map_palestras(parsed["palestra"], major_event_id_by_year_ref, now)

    all_referenced_cpfs = collect_referenced_cpfs(parsed, palestra_seeds)
    people_rows, cpf_to_person_id = map_people(parsed["dados"], all_referenced_cpfs, now)

    (
        major_event_subscription_rows,
        skipped_major_subscriptions,
        paid_by_major_event,
    ) = map_major_event_subscriptions(
        parsed["inscricao"], cpf_to_person_id, major_event_id_by_year_ref, now
    )

    (
        event_subscription_rows,
        skipped_event_subscriptions,
    ) = map_event_subscriptions(
        parsed["participacao_minicurso"],
        parsed["participacao_palestra"],
        cpf_to_person_id,
        minicurso_seeds,
        palestra_seeds,
        now,
    )

    (
        event_attendance_rows,
        skipped_attendances,
    ) = map_event_attendances(parsed["participacao_minicurso"], cpf_to_person_id, minicurso_seeds, now)

    (
        event_lecturer_rows,
        skipped_lecturers,
    ) = map_event_lecturers(
        parsed["ministrante_minicurso"],
        palestra_seeds,
        cpf_to_person_id,
        minicurso_seeds,
        now,
    )

    event_rows = build_event_rows(
        minicurso_seeds,
        palestra_seeds,
        event_group_id_by_type,
        now,
    )

    major_event_rows = build_major_event_rows(
        parsed["ano_referencia"],
        major_event_id_by_year_ref,
        event_rows,
        paid_by_major_event,
        now,
    )

    return MigrationPayload(
        major_events=major_event_rows,
        event_groups=event_group_rows,
        events=event_rows,
        people=people_rows,
        major_event_subscriptions=major_event_subscription_rows,
        event_subscriptions=event_subscription_rows,
        event_attendances=event_attendance_rows,
        event_lecturers=event_lecturer_rows,
        skipped_major_subscriptions=skipped_major_subscriptions,
        skipped_event_subscriptions=skipped_event_subscriptions,
        skipped_attendances=skipped_attendances,
        skipped_lecturers=skipped_lecturers,
    )


def map_major_event_ids(ano_rows: list[dict[str, Any]]) -> dict[int, str]:
    mapping: dict[int, str] = {}
    for row in ano_rows:
        year_ref_id = decimal_to_int(row.get("idAno_Referencia"))
        if year_ref_id is None:
            continue
        mapping[year_ref_id] = build_prefixed_id(PREFIX, "major-event", "ano", year_ref_id)
    return mapping


def map_minicursos(
    legacy_rows: list[dict[str, Any]],
    major_event_id_by_year_ref: dict[int, str],
    fallback_now: datetime,
) -> dict[int, dict[str, Any]]:
    rows: dict[int, dict[str, Any]] = {}

    for row in legacy_rows:
        minicurso_id = decimal_to_int(row.get("idMinicurso"))
        year_ref_id = decimal_to_int(row.get("idAno_ReferenciaFK"))
        if minicurso_id is None or year_ref_id is None:
            continue
        major_event_id = major_event_id_by_year_ref.get(year_ref_id)
        if major_event_id is None:
            continue

        event_date = parse_mysql_date(row.get("data"))
        start_time = parse_mysql_time(row.get("hora_inicio"))
        end_time = parse_mysql_time(row.get("hora_termino"))
        start_date = combine_date_and_time(event_date, start_time) or at_start_of_day(event_date) or fallback_now
        end_date = combine_date_and_time(event_date, end_time) or start_date
        if end_date < start_date:
            end_date = start_date

        workload_hours = decimal_to_int(row.get("cargahoraria"))

        rows[minicurso_id] = {
            "id": build_prefixed_id(PREFIX, "event", "minicurso", minicurso_id),
            "name": coerce_text(row.get("nome"), fix_mojibake=True) or f"Minicurso {minicurso_id}",
            "type": "MINICURSO",
            "emoji": "🧪",
            "description": coerce_text(row.get("descricao"), fix_mojibake=True),
            "shortDescription": strip_html(row.get("descricao")),
            "creditMinutes": (workload_hours * 60) if workload_hours is not None else None,
            "startDate": start_date,
            "endDate": end_date,
            "locationDescription": coerce_text(row.get("local"), fix_mojibake=True),
            "majorEventId": major_event_id,
            "slots": decimal_to_int(row.get("vagas")),
            "createdAt": parse_mysql_datetime(row.get("create_time")) or start_date,
            "speakerCpf": None,
        }

    return rows


def map_palestras(
    legacy_rows: list[dict[str, Any]],
    major_event_id_by_year_ref: dict[int, str],
    fallback_now: datetime,
) -> dict[int, dict[str, Any]]:
    rows: dict[int, dict[str, Any]] = {}

    for row in legacy_rows:
        palestra_id = decimal_to_int(row.get("idPalestra"))
        year_ref_id = decimal_to_int(row.get("idAno_ReferenciaFK"))
        if palestra_id is None or year_ref_id is None:
            continue
        major_event_id = major_event_id_by_year_ref.get(year_ref_id)
        if major_event_id is None:
            continue

        event_date = parse_mysql_date(row.get("data"))
        start_time = parse_mysql_time(row.get("hora_inicio"))
        end_time = parse_mysql_time(row.get("hora_termino"))
        start_date = combine_date_and_time(event_date, start_time) or at_start_of_day(event_date) or fallback_now
        end_date = combine_date_and_time(event_date, end_time) or start_date
        if end_date < start_date:
            end_date = start_date

        rows[palestra_id] = {
            "id": build_prefixed_id(PREFIX, "event", "palestra", palestra_id),
            "name": coerce_text(row.get("nome"), fix_mojibake=True) or f"Palestra {palestra_id}",
            "type": "PALESTRA",
            "emoji": "🎤",
            "description": coerce_text(row.get("descricao"), fix_mojibake=True),
            "shortDescription": strip_html(row.get("descricao")),
            "creditMinutes": None,
            "startDate": start_date,
            "endDate": end_date,
            "locationDescription": coerce_text(row.get("local"), fix_mojibake=True),
            "majorEventId": major_event_id,
            "slots": None,
            "createdAt": parse_mysql_datetime(row.get("create_time")) or start_date,
            "speakerCpf": normalize_cpf(row.get("CPFusuarioFK")),
        }

    return rows


def collect_referenced_cpfs(
    parsed: dict[str, list[dict[str, Any]]],
    palestra_seeds: dict[int, dict[str, Any]],
) -> set[str]:
    cpfs: set[str] = set()

    for row in parsed["dados"]:
        cpf = normalize_cpf(row.get("CPF"))
        if cpf:
            cpfs.add(cpf)

    for row in parsed["inscricao"]:
        cpf = normalize_cpf(row.get("CPFdadosFK"))
        if cpf:
            cpfs.add(cpf)

    for row in parsed["participacao_minicurso"]:
        cpf = normalize_cpf(row.get("CPFusuarioFK"))
        if cpf:
            cpfs.add(cpf)

    for row in parsed["participacao_palestra"]:
        cpf = normalize_cpf(row.get("CPFusuarioFK"))
        if cpf:
            cpfs.add(cpf)

    for row in parsed["ministrante_minicurso"]:
        cpf = normalize_cpf(row.get("CPFusuarioFK"))
        if cpf:
            cpfs.add(cpf)

    for seed in palestra_seeds.values():
        cpf = seed.get("speakerCpf")
        if cpf:
            cpfs.add(cpf)

    return cpfs


def map_people(
    legacy_rows: list[dict[str, Any]],
    required_cpfs: set[str],
    fallback_now: datetime,
) -> tuple[list[dict[str, Any]], dict[str, str]]:
    people_by_cpf: dict[str, dict[str, Any]] = {}

    for row in legacy_rows:
        cpf = normalize_cpf(row.get("CPF"))
        if cpf is None:
            continue
        created_at = parse_mysql_datetime(row.get("create_time")) or fallback_now
        people_by_cpf[cpf] = {
            "id": uuid7_string(),
            "name": normalize_person_name(row.get("nome")) or f"Pessoa {cpf}",
            "email": normalize_email(row.get("email")),
            "identityDocument": cpf,
            "academicId": None,
            "externalRef": build_prefixed_id(PREFIX, "legacy-cpf", cpf),
            "createdAt": created_at,
            "updatedAt": fallback_now,
        }

    for cpf in sorted(required_cpfs):
        if cpf in people_by_cpf:
            continue
        people_by_cpf[cpf] = {
            "id": uuid7_string(),
            "name": f"Pessoa {cpf}",
            "email": None,
            "identityDocument": cpf,
            "academicId": None,
            "externalRef": build_prefixed_id(PREFIX, "legacy-cpf", cpf),
            "createdAt": fallback_now,
            "updatedAt": fallback_now,
        }

    cpf_to_person_id = {cpf: row["id"] for cpf, row in people_by_cpf.items()}
    rows = [people_by_cpf[cpf] for cpf in sorted(people_by_cpf)]
    return rows, cpf_to_person_id


def map_major_event_subscriptions(
    legacy_rows: list[dict[str, Any]],
    cpf_to_person_id: dict[str, str],
    major_event_id_by_year_ref: dict[int, str],
    fallback_now: datetime,
) -> tuple[list[dict[str, Any]], int, dict[str, bool]]:
    rows_by_id: dict[str, dict[str, Any]] = {}
    skipped = 0
    paid_by_major_event: dict[str, bool] = {}

    for row in legacy_rows:
        cpf = normalize_cpf(row.get("CPFdadosFK"))
        year_ref_id = decimal_to_int(row.get("idAno_ReferenciaFK"))
        inscription_id = decimal_to_int(row.get("idInscricao"))
        if cpf is None or year_ref_id is None or inscription_id is None:
            skipped += 1
            continue

        person_id = cpf_to_person_id.get(cpf)
        major_event_id = major_event_id_by_year_ref.get(year_ref_id)
        if person_id is None or major_event_id is None:
            skipped += 1
            continue

        amount_paid = decimal_to_int(row.get("total"))
        if amount_paid is not None and amount_paid > 0:
            paid_by_major_event[major_event_id] = True

        status = decimal_to_int(row.get("status")) or 0
        subscription_status = "CONFIRMED" if status == 1 else "WAITING_RECEIPT_UPLOAD"
        created_at = parse_mysql_datetime(row.get("create_time")) or fallback_now

        subscription_id = deterministic_prefixed_id(
            PREFIX, f"legacy2-major-sub:{inscription_id}:{cpf}:{year_ref_id}"
        )
        rows_by_id[subscription_id] = {
            "id": subscription_id,
            "majorEventId": major_event_id,
            "personId": person_id,
            "amountPaid": amount_paid,
            "paymentDate": created_at,
            "paymentTier": None,
            "subscriptionStatus": subscription_status,
            "createdAt": created_at,
            "createdById": None,
        }

    return sorted(rows_by_id.values(), key=lambda item: item["id"]), skipped, paid_by_major_event


def map_event_subscriptions(
    minicurso_rows: list[dict[str, Any]],
    palestra_rows: list[dict[str, Any]],
    cpf_to_person_id: dict[str, str],
    minicurso_seeds: dict[int, dict[str, Any]],
    palestra_seeds: dict[int, dict[str, Any]],
    fallback_now: datetime,
) -> tuple[list[dict[str, Any]], int]:
    rows_by_id: dict[str, dict[str, Any]] = {}
    skipped = 0

    for row in minicurso_rows:
        cpf = normalize_cpf(row.get("CPFusuarioFK"))
        minicurso_id = decimal_to_int(row.get("idMinicursoFK"))
        if cpf is None or minicurso_id is None:
            skipped += 1
            continue
        person_id = cpf_to_person_id.get(cpf)
        seed = minicurso_seeds.get(minicurso_id)
        if person_id is None or seed is None:
            skipped += 1
            continue

        subscription_id = deterministic_prefixed_id(
            PREFIX, f"legacy2-event-sub:minicurso:{cpf}:{minicurso_id}"
        )
        rows_by_id[subscription_id] = {
            "id": subscription_id,
            "eventId": seed["id"],
            "personId": person_id,
            "createdAt": parse_mysql_datetime(row.get("create_time")) or seed["startDate"] or fallback_now,
            "createdById": None,
        }

    for row in palestra_rows:
        cpf = normalize_cpf(row.get("CPFusuarioFK"))
        palestra_id = decimal_to_int(row.get("idPalestraFK"))
        if cpf is None or palestra_id is None:
            skipped += 1
            continue
        person_id = cpf_to_person_id.get(cpf)
        seed = palestra_seeds.get(palestra_id)
        if person_id is None or seed is None:
            skipped += 1
            continue

        subscription_id = deterministic_prefixed_id(
            PREFIX, f"legacy2-event-sub:palestra:{cpf}:{palestra_id}"
        )
        rows_by_id[subscription_id] = {
            "id": subscription_id,
            "eventId": seed["id"],
            "personId": person_id,
            "createdAt": parse_mysql_datetime(row.get("create_time")) or seed["startDate"] or fallback_now,
            "createdById": None,
        }

    return sorted(rows_by_id.values(), key=lambda item: item["id"]), skipped


def map_event_attendances(
    legacy_rows: list[dict[str, Any]],
    cpf_to_person_id: dict[str, str],
    minicurso_seeds: dict[int, dict[str, Any]],
    fallback_now: datetime,
) -> tuple[list[dict[str, Any]], int]:
    rows_by_pair: dict[tuple[str, str], dict[str, Any]] = {}
    skipped = 0

    for row in legacy_rows:
        has_presence = decimal_to_int(row.get("presenca")) == 1
        if not has_presence:
            continue

        cpf = normalize_cpf(row.get("CPFusuarioFK"))
        minicurso_id = decimal_to_int(row.get("idMinicursoFK"))
        if cpf is None or minicurso_id is None:
            skipped += 1
            continue
        person_id = cpf_to_person_id.get(cpf)
        seed = minicurso_seeds.get(minicurso_id)
        if person_id is None or seed is None:
            skipped += 1
            continue

        pair = (person_id, seed["id"])
        attended_at = parse_mysql_datetime(row.get("create_time")) or seed["startDate"] or fallback_now
        rows_by_pair[pair] = {
            "personId": pair[0],
            "eventId": pair[1],
            "attendedAt": attended_at,
            "createdAt": attended_at,
            "createdById": None,
        }

    rows = [rows_by_pair[key] for key in sorted(rows_by_pair)]
    return rows, skipped


def map_event_lecturers(
    ministrante_rows: list[dict[str, Any]],
    palestra_seeds: dict[int, dict[str, Any]],
    cpf_to_person_id: dict[str, str],
    minicurso_seeds: dict[int, dict[str, Any]],
    fallback_now: datetime,
) -> tuple[list[dict[str, Any]], int]:
    rows_by_pair: dict[tuple[str, str], dict[str, Any]] = {}
    skipped = 0

    for row in ministrante_rows:
        cpf = normalize_cpf(row.get("CPFusuarioFK"))
        minicurso_id = decimal_to_int(row.get("idMinicursoFK"))
        if cpf is None or minicurso_id is None:
            skipped += 1
            continue
        person_id = cpf_to_person_id.get(cpf)
        seed = minicurso_seeds.get(minicurso_id)
        if person_id is None or seed is None:
            skipped += 1
            continue
        pair = (seed["id"], person_id)
        created_at = parse_mysql_datetime(row.get("create_time")) or seed["startDate"] or fallback_now
        rows_by_pair[pair] = {
            "eventId": pair[0],
            "personId": pair[1],
            "createdAt": created_at,
            "createdById": None,
        }

    for seed in palestra_seeds.values():
        cpf = seed.get("speakerCpf")
        if not cpf:
            continue
        person_id = cpf_to_person_id.get(cpf)
        if person_id is None:
            skipped += 1
            continue
        pair = (seed["id"], person_id)
        rows_by_pair[pair] = {
            "eventId": pair[0],
            "personId": pair[1],
            "createdAt": seed["createdAt"] or fallback_now,
            "createdById": None,
        }

    rows = [rows_by_pair[key] for key in sorted(rows_by_pair)]
    return rows, skipped


def build_event_groups(now: datetime) -> list[dict[str, Any]]:
    return [
        {
            "id": build_prefixed_id(PREFIX, "event-group", "palestras"),
            "name": "Palestras (SECOMPP legado 2)",
            "type": "PALESTRA",
            "createdAt": now,
            "updatedAt": now,
        },
        {
            "id": build_prefixed_id(PREFIX, "event-group", "minicursos"),
            "name": "Minicursos (SECOMPP legado 2)",
            "type": "MINICURSO",
            "createdAt": now,
            "updatedAt": now,
        },
    ]


def build_event_rows(
    minicurso_seeds: dict[int, dict[str, Any]],
    palestra_seeds: dict[int, dict[str, Any]],
    event_group_id_by_type: dict[str, str],
    fallback_now: datetime,
) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for seed in [*minicurso_seeds.values(), *palestra_seeds.values()]:
        rows.append(
            {
                "id": seed["id"],
                "name": seed["name"],
                "creditMinutes": seed["creditMinutes"],
                "startDate": seed["startDate"],
                "endDate": seed["endDate"],
                "type": seed["type"],
                "emoji": seed["emoji"],
                "description": seed["description"],
                "shortDescription": seed["shortDescription"],
                "latitude": None,
                "longitude": None,
                "locationDescription": seed["locationDescription"],
                "majorEventId": seed["majorEventId"],
                "eventGroupId": event_group_id_by_type.get(seed["type"]),
                "allowSubscription": True,
                "slots": seed["slots"],
                "shouldIssueCertificate": False,
                "shouldCollectAttendance": True,
                "isOnlineAttendanceAllowed": False,
                "onlineAttendanceCode": None,
                "onlineAttendanceStartDate": None,
                "onlineAttendanceEndDate": None,
                "publiclyVisible": True,
                "youtubeCode": None,
                "buttonText": None,
                "buttonLink": None,
                "createdAt": seed["createdAt"] or fallback_now,
                "createdById": None,
                "updatedAt": fallback_now,
            }
        )

    return sorted(rows, key=lambda item: item["id"])


def build_major_event_rows(
    ano_rows: list[dict[str, Any]],
    major_event_id_by_year_ref: dict[int, str],
    event_rows: list[dict[str, Any]],
    paid_by_major_event: dict[str, bool],
    fallback_now: datetime,
) -> list[dict[str, Any]]:
    date_ranges: dict[str, tuple[datetime, datetime]] = {}
    for event in event_rows:
        major_event_id = event.get("majorEventId")
        start_date = event.get("startDate")
        end_date = event.get("endDate")
        if major_event_id is None or start_date is None or end_date is None:
            continue
        existing = date_ranges.get(major_event_id)
        if existing is None:
            date_ranges[major_event_id] = (start_date, end_date)
            continue
        date_ranges[major_event_id] = (min(existing[0], start_date), max(existing[1], end_date))

    rows: list[dict[str, Any]] = []
    for row in ano_rows:
        year_ref_id = decimal_to_int(row.get("idAno_Referencia"))
        year = decimal_to_int(row.get("ano"))
        if year_ref_id is None:
            continue
        major_event_id = major_event_id_by_year_ref.get(year_ref_id)
        if major_event_id is None:
            continue

        date_range = date_ranges.get(major_event_id)
        default_start = at_start_of_day(date(year or 2000, 1, 1))
        default_end = at_start_of_day(date(year or 2000, 12, 31))
        start_date = date_range[0] if date_range else default_start or fallback_now
        end_date = date_range[1] if date_range else default_end or start_date
        if end_date < start_date:
            end_date = start_date

        rows.append(
            {
                "id": major_event_id,
                "name": f"SECOMPP {year}" if year else f"SECOMPP ano {year_ref_id}",
                "startDate": start_date,
                "endDate": end_date,
                "description": "Importado de secompp2.sql",
                "isPaymentRequired": paid_by_major_event.get(major_event_id, False),
                "createdAt": parse_mysql_datetime(row.get("create_time")) or start_date,
                "updatedAt": fallback_now,
            }
        )

    return sorted(rows, key=lambda item: item["id"])


def write_payload(database_url: str, payload: MigrationPayload) -> None:
    try:
        import psycopg
    except ImportError as error:
        raise RuntimeError(
            "Missing dependency 'psycopg'. Install with: pip install \"psycopg[binary]\""
        ) from error

    with psycopg.connect(database_url) as connection:
        with connection.cursor() as cursor:
            old_person_id_to_external_ref, resolved_person_id_by_external_ref = (
                reconcile_people_ids_with_database(cursor, payload.people)
            )
            rebind_people_foreign_keys(
                payload,
                old_person_id_to_external_ref,
                resolved_person_id_by_external_ref,
            )

            execute_many_if_any(
                cursor,
                """
                INSERT INTO major_events (
                  id, name, "startDate", "endDate", description, "isPaymentRequired", "createdAt", "updatedAt"
                )
                VALUES (
                  %(id)s, %(name)s, %(startDate)s, %(endDate)s, %(description)s, %(isPaymentRequired)s, %(createdAt)s, %(updatedAt)s
                )
                ON CONFLICT (id) DO UPDATE SET
                  name = EXCLUDED.name,
                  "startDate" = EXCLUDED."startDate",
                  "endDate" = EXCLUDED."endDate",
                  description = EXCLUDED.description,
                  "isPaymentRequired" = EXCLUDED."isPaymentRequired",
                  "updatedAt" = EXCLUDED."updatedAt"
                """,
                payload.major_events,
            )

            event_groups = [
                {
                    "id": row["id"],
                    "name": row["name"],
                    "createdAt": row["createdAt"],
                    "updatedAt": row["updatedAt"],
                }
                for row in payload.event_groups
            ]
            execute_many_if_any(
                cursor,
                """
                INSERT INTO event_groups (
                  id, name, "createdAt", "updatedAt"
                )
                VALUES (
                  %(id)s, %(name)s, %(createdAt)s, %(updatedAt)s
                )
                ON CONFLICT (id) DO UPDATE SET
                  name = EXCLUDED.name,
                  "updatedAt" = EXCLUDED."updatedAt"
                """,
                event_groups,
            )

            execute_many_if_any(
                cursor,
                """
                INSERT INTO events (
                  id, name, "creditMinutes", "startDate", "endDate", type, emoji,
                  description, "shortDescription", latitude, longitude, "locationDescription",
                  "majorEventId", "eventGroupId", "allowSubscription", slots,
                  "shouldIssueCertificate", "shouldCollectAttendance",
                  "isOnlineAttendanceAllowed", "onlineAttendanceCode",
                  "onlineAttendanceStartDate", "onlineAttendanceEndDate",
                  "publiclyVisible", "youtubeCode", "buttonText", "buttonLink",
                  "createdAt", "createdById", "updatedAt"
                )
                VALUES (
                  %(id)s, %(name)s, %(creditMinutes)s, %(startDate)s, %(endDate)s, %(type)s, %(emoji)s,
                  %(description)s, %(shortDescription)s, %(latitude)s, %(longitude)s, %(locationDescription)s,
                  %(majorEventId)s, %(eventGroupId)s, %(allowSubscription)s, %(slots)s,
                  %(shouldIssueCertificate)s, %(shouldCollectAttendance)s,
                  %(isOnlineAttendanceAllowed)s, %(onlineAttendanceCode)s,
                  %(onlineAttendanceStartDate)s, %(onlineAttendanceEndDate)s,
                  %(publiclyVisible)s, %(youtubeCode)s, %(buttonText)s, %(buttonLink)s,
                  %(createdAt)s, %(createdById)s, %(updatedAt)s
                )
                ON CONFLICT (id) DO UPDATE SET
                  name = EXCLUDED.name,
                  "creditMinutes" = EXCLUDED."creditMinutes",
                  "startDate" = EXCLUDED."startDate",
                  "endDate" = EXCLUDED."endDate",
                  type = EXCLUDED.type,
                  emoji = EXCLUDED.emoji,
                  description = EXCLUDED.description,
                  "shortDescription" = EXCLUDED."shortDescription",
                  latitude = EXCLUDED.latitude,
                  longitude = EXCLUDED.longitude,
                  "locationDescription" = EXCLUDED."locationDescription",
                  "majorEventId" = EXCLUDED."majorEventId",
                  "eventGroupId" = EXCLUDED."eventGroupId",
                  "allowSubscription" = EXCLUDED."allowSubscription",
                  slots = EXCLUDED.slots,
                  "shouldIssueCertificate" = EXCLUDED."shouldIssueCertificate",
                  "shouldCollectAttendance" = EXCLUDED."shouldCollectAttendance",
                  "isOnlineAttendanceAllowed" = EXCLUDED."isOnlineAttendanceAllowed",
                  "onlineAttendanceCode" = EXCLUDED."onlineAttendanceCode",
                  "onlineAttendanceStartDate" = EXCLUDED."onlineAttendanceStartDate",
                  "onlineAttendanceEndDate" = EXCLUDED."onlineAttendanceEndDate",
                  "publiclyVisible" = EXCLUDED."publiclyVisible",
                  "youtubeCode" = EXCLUDED."youtubeCode",
                  "buttonText" = EXCLUDED."buttonText",
                  "buttonLink" = EXCLUDED."buttonLink",
                  "updatedAt" = EXCLUDED."updatedAt"
                """,
                payload.events,
            )

            execute_many_if_any(
                cursor,
                """
                INSERT INTO people (
                  id, name, email, "identityDocument", "academicId", "externalRef", "createdAt", "updatedAt"
                )
                VALUES (
                  %(id)s, %(name)s, %(email)s, %(identityDocument)s, %(academicId)s, %(externalRef)s, %(createdAt)s, %(updatedAt)s
                )
                ON CONFLICT ("externalRef") DO UPDATE SET
                  name = EXCLUDED.name,
                  email = EXCLUDED.email,
                  "identityDocument" = EXCLUDED."identityDocument",
                  "academicId" = EXCLUDED."academicId",
                  "updatedAt" = EXCLUDED."updatedAt"
                """,
                payload.people,
            )

            execute_many_if_any(
                cursor,
                """
                INSERT INTO major_event_subscriptions (
                  id, "majorEventId", "personId", "amountPaid", "paymentDate",
                  "paymentTier", "subscriptionStatus", "createdAt", "createdById"
                )
                VALUES (
                  %(id)s, %(majorEventId)s, %(personId)s, %(amountPaid)s, %(paymentDate)s,
                  %(paymentTier)s, %(subscriptionStatus)s, %(createdAt)s, %(createdById)s
                )
                ON CONFLICT (id) DO UPDATE SET
                  "majorEventId" = EXCLUDED."majorEventId",
                  "personId" = EXCLUDED."personId",
                  "amountPaid" = EXCLUDED."amountPaid",
                  "paymentDate" = EXCLUDED."paymentDate",
                  "paymentTier" = EXCLUDED."paymentTier",
                  "subscriptionStatus" = EXCLUDED."subscriptionStatus",
                  "createdAt" = EXCLUDED."createdAt",
                  "createdById" = EXCLUDED."createdById"
                """,
                payload.major_event_subscriptions,
            )

            execute_many_if_any(
                cursor,
                """
                INSERT INTO event_subscriptions (
                  id, "eventId", "personId", "createdAt", "createdById"
                )
                VALUES (
                  %(id)s, %(eventId)s, %(personId)s, %(createdAt)s, %(createdById)s
                )
                ON CONFLICT (id) DO UPDATE SET
                  "eventId" = EXCLUDED."eventId",
                  "personId" = EXCLUDED."personId",
                  "createdAt" = EXCLUDED."createdAt",
                  "createdById" = EXCLUDED."createdById"
                """,
                payload.event_subscriptions,
            )

            execute_many_if_any(
                cursor,
                """
                INSERT INTO event_attendances (
                  "personId", "eventId", "attendedAt", "createdAt", "createdById"
                )
                VALUES (
                  %(personId)s, %(eventId)s, %(attendedAt)s, %(createdAt)s, %(createdById)s
                )
                ON CONFLICT ("personId", "eventId") DO UPDATE SET
                  "attendedAt" = EXCLUDED."attendedAt",
                  "createdAt" = EXCLUDED."createdAt",
                  "createdById" = EXCLUDED."createdById"
                """,
                payload.event_attendances,
            )

            execute_many_if_any(
                cursor,
                """
                INSERT INTO event_lecturers (
                  "eventId", "personId", "createdAt", "createdById"
                )
                VALUES (
                  %(eventId)s, %(personId)s, %(createdAt)s, %(createdById)s
                )
                ON CONFLICT ("eventId", "personId") DO UPDATE SET
                  "createdAt" = EXCLUDED."createdAt",
                  "createdById" = EXCLUDED."createdById"
                """,
                payload.event_lecturers,
            )


def reconcile_people_ids_with_database(
    cursor: Any, people_rows: list[dict[str, Any]]
) -> tuple[dict[str, str], dict[str, str]]:
    old_person_id_to_external_ref: dict[str, str] = {
        row["id"]: row["externalRef"] for row in people_rows
    }
    resolved_person_id_by_external_ref: dict[str, str] = {
        row["externalRef"]: row["id"] for row in people_rows
    }

    external_refs = list(resolved_person_id_by_external_ref.keys())
    if external_refs:
        cursor.execute(
            'SELECT id, "externalRef" FROM people WHERE "externalRef" = ANY(%s)',
            (external_refs,),
        )
        for person_id, external_ref in cursor.fetchall():
            resolved_person_id_by_external_ref[str(external_ref)] = str(person_id)

    for row in people_rows:
        row["id"] = resolved_person_id_by_external_ref[row["externalRef"]]

    return old_person_id_to_external_ref, resolved_person_id_by_external_ref


def rebind_people_foreign_keys(
    payload: MigrationPayload,
    old_person_id_to_external_ref: dict[str, str],
    resolved_person_id_by_external_ref: dict[str, str],
) -> None:
    collections_and_keys = (
        (payload.major_event_subscriptions, "personId"),
        (payload.event_subscriptions, "personId"),
        (payload.event_attendances, "personId"),
        (payload.event_lecturers, "personId"),
    )

    for rows, key in collections_and_keys:
        for row in rows:
            old_person_id = row.get(key)
            if not isinstance(old_person_id, str):
                raise RuntimeError("Unexpected personId type while rebinding references.")
            external_ref = old_person_id_to_external_ref.get(old_person_id)
            if external_ref is None:
                raise RuntimeError(f"Missing externalRef mapping for personId '{old_person_id}'.")
            resolved_person_id = resolved_person_id_by_external_ref.get(external_ref)
            if resolved_person_id is None:
                raise RuntimeError(
                    f"Missing resolved personId for externalRef '{external_ref}'."
                )
            row[key] = resolved_person_id


def execute_many_if_any(cursor: Any, query: str, rows: list[dict[str, Any]]) -> None:
    if not rows:
        return
    cursor.executemany(query, rows)


if __name__ == "__main__":
    main()
