.angular
.git
.github
.nx/cache
.nx/workspace-data
.vscode
coverage
dist
node_modules
tmp

.DS_Store
*.log
*.local

docker
import
*.csv
*.sql

apps/*
!apps/events-backend
!apps/events-backend/**
!shared-data-types
!shared-data-types/**
!shared-utils
!shared-utils/**
!certificate-templates
!certificate-templates/**
