name: backend-ci

on:
  push:
    paths: — 'backend/**'
    branches:
      - "**"

  pull_request:
    paths: — 'backend/**'
    branches:
      - "**"

jobs:
  build_functions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        working-directory: ./backend
        run: bun install --frozen-lockfile

      - name: Build functions
        working-directory: ./backend
        run: bun run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Functions-artifacts
          path: backend/dist/
