name: Build Functions

on: 
  push:
    paths:
     — 'functions/**'
    branches:
     - '**'

  pull_request:
    paths:
     — 'functions/**'
    branches:
     - '**'

jobs:
  build_functions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: functions/package-lock.json

      - name: Install dependencies
        run: cd functions && npm ci
        
      - name: Build functions
        run: npm run build
