name: Cloud functions

on: 
  push:
    paths:
     — 'functions/**'
    branches:
     - '**'

  pull_request:
    paths:
     — 'functions/**'
    branches:
     - '**'

jobs:
  build_functions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        working-directory: ./functions
        run: bun install --frozen-lockfile
        
      - name: Build functions
        working-directory: ./functions
        run: bun build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        working-directory: ./functions
        with:
          name: Functions-artifacts
          path: dist/
