name: Build Functions

on: 
  push:
    paths:
     — 'functions/**'
    branches:
     - '**'

  pull_request:
    paths:
     — 'functions/**'
    branches:
     - '**'

jobs:
  build_functions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: functions/package-lock.json

      - name: Install dependencies
        run: cd functions && yarn install --frozen-lockfile
        
      - name: Build functions
        run: yarn build
