name: Cloud functions

on: 
  push:
    paths:
     — 'functions/**'
    branches:
     - '**'

  pull_request:
    paths:
     — 'functions/**'
    branches:
     - '**'

jobs:
  build_functions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: functions/yarn.lock

      - name: Install dependencies
        working-directory: ./functions
        run: yarn install --frozen-lockfile
        
      - name: Build functions
        working-directory: ./functions
        run: cd functions yarn build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        working-directory: ./functions
        with:
          name: Functions-artifacts
          path: dist/
