name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/workflows/frontend/setup-deps.yml

      - uses: ./.github/workflows/frontend/build.yml

      - uses: ./.github/workflows/frontend/lint.yml

      - uses: ./.github/workflows/frontend/tests-upload.yml

      

