# Attribution: Dave Sugden
# https://davelms.medium.com/deploy-firebase-functions-using-github-actions-7dbafbd4df77
name: Deploy functions

on:
  push:
    paths:
     — 'functions/**'
    branches:
     - 'main'

jobs:
  build_functions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        working-directory: ./functions
        run: bun install --frozen-lockfile
        
      - name: Build functions
        working-directory: ./functions
        run: bun run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Functions-artifacts
          path: functions/lib/

  deploy:
    needs: build_functions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: Functions-artifacts
          path: functions/lib/

      - name: Create Service Account key
        working-directory: ./functions
        run: echo '${{ secrets.FIREBASE_FUNCTIONS_ACCOUNT }}' > $HOME/gcloud.json
         
      - name: Deploy Cloud Functions
        working-directory: ./functions
        run: export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json && npx firebase-tools deploy --only functions --json
