# Attribution: Dave Sugden
# https://davelms.medium.com/deploy-firebase-functions-using-github-actions-7dbafbd4df77
name: Deploy functions

on: 
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build_functions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: functions/yarn.lock

      - name: Install dependencies
        run: cd functions && yarn install --frozen-lockfile && yarn add @angular/cli@latest
        
      - name: Build functions
        run: yarn build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Functions-artifacts
          path: functions/dist/

  deploy:
    needs: build_functions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: Functions-artifacts
          path: functions/dist/

      - name: Create Service Account key
        run: echo '${{ secrets.FIREBASE_FUNCTIONS_ACCOUNT }}' > $HOME/gcloud.json
         
      - name: Deploy Cloud Functions
        run: export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json && npx firebase-tools deploy --only functions --json
