# Attribution: Oleksii Holub (Tyrrrz)
# https://github.com/Tyrrrz/DiscordChatExporter
name: Push to GitHub Container Registry

on:
  workflow_dispatch:
  push:
    branches:
      - nextjs
    tags:
      - "*"

env:
  IMAGE_NAME: fct_app

jobs:
  pack:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      actions: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: >
          docker buildx build .
          --file ./Dockerfile
          --platform linux/amd64
          --output type=tar,dest=FCT-App.Docker.tar

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FCT-App.Docker
          path: FCT-App.Docker.tar
          if-no-files-found: error

  release:
      needs: pack
      permissions:
        contents: write

      runs-on: ubuntu-latest
      steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh release create latest
          --repo ${{ github.event.repository.full_name }}
          --title latest
          --latest
          --generate-notes
          --verify-tag
          # TODO: Change me
          --target nextjs

  deploy:
    needs: release
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
