name: docs

on:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
    branches:
      - '**'

  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install, build, and upload
        uses: withastro/action@v2
        with:
          package-manager: bun@latest
          path: docs

  scrape:
    if: ${{github.ref == 'refs/heads/main'}}
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Wait for Cloudflare to deploy the site
      - name: Sleep for 5 minutes
        run: sleep 5m
        shell: bash

      - name: Algolia crawler creation and crawl
        uses: algolia/algoliasearch-crawler-github-actions@v1.1.10
        id: algolia_crawler
        with:
          crawler-user-id: ${{ secrets.ALGOLIA_CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.ALGOLIA_CRAWLER_API_KEY }}
          algolia-app-id: ${{ secrets.ALGOLIA_APP_ID }}
          algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
          site-url: 'https://docs.fctapp.cacic.dev.br'
          crawler-name: 'fctapp-yudi'
