name: docs

on:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
    branches:
      - '**'

  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install, build, and upload
        uses: withastro/action@v2
        with:
          package-manager: bun@latest
          path: docs

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.DOCS_CLOUDFLARE_API_TOKEN }}
          accountId: 034f5089bb082eb57cefc432b42b984d
          projectName: fct-app-docs
          directory: dist/
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          workingDirectory: docs
          wranglerVersion: '3'

  scrape:
    if: ${{github.ref == 'refs/heads/main'}}
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Wait for Cloudflare to deploy the site
      - name: Sleep for 4 minutes
        run: sleep 4m
        shell: bash

      - name: Algolia crawler creation and crawl
        uses: algolia/algoliasearch-crawler-github-actions@v1.1.10
        id: algolia_crawler
        with:
          crawler-user-id: ${{ secrets.DOCS_ALGOLIA_CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.DOCS_ALGOLIA_CRAWLER_API_KEY }}
          algolia-app-id: ${{ secrets.DOCS_ALGOLIA_APP_ID }}
          algolia-api-key: ${{ secrets.DOCS_ALGOLIA_API_KEY }}
          site-url: 'https://docs.fctapp.cacic.dev.br'
          crawler-name: 'fctapp-yudi'
