name: frontend-ci

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
      - '.github/workflows/frontend-deploy.yml'
    branches:
      - '**'

  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
      - '.github/workflows/frontend-deploy.yml'
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        working-directory: ./frontend
        run: bun install --frozen-lockfile

      - name: Build for production
        working-directory: ./frontend
        run: bun run build --configuration=production --verbose

      - name: Upload artifacts

        uses: actions/upload-artifact@v4
        with:
          name: Build-artifacts
          path: frontend/dist/

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        working-directory: ./frontend
        run: bun install --frozen-lockfile

      - name: Lint
        working-directory: ./frontend
        run: bun run lint

  unit-tests:
    if: ${{ github.event_name == 'pull_request' }}
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        working-directory: ./frontend
        run: bun install --frozen-lockfile

      - name: Unit tests
        working-directory: ./frontend
        run: bun run test --no-watch --no-progress --browsers=ChromeHeadless

  unit-tests-upload:
    # This job uses a secret
    # Pull requests are untrusted
    if: ${{ github.event_name == 'push' }}
    name: Unit tests and upload to Codecov
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        working-directory: ./frontend
        run: bun install --frozen-lockfile

      - name: Unit tests
        working-directory: ./frontend
        run: bun run test --no-watch --no-progress --browsers=ChromeHeadless

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: frontend_unit
          files: frontend/coverage/lcov.info
