# Attribution: Oleksii Holub (Tyrrrz)
# https://github.com/Tyrrrz/DiscordChatExporter
name: main

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build for production
        run: bun run build --configuration=production
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build-artifacts
          path: dist/
  
  release:
      if: ${{ github.ref_type == 'tag' }}
      needs: build
      permissions:
        contents: write

      runs-on: ubuntu-latest
      steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh release create ${{ github.ref_name }}
          --repo ${{ github.event.repository.full_name }}
          --title ${{ github.ref_name }}
          --generate-notes
          --verify-tag

  deploy:
    needs: release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: Build-artifacts
          path: dist/

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FCT_PP }}'
          channelId: live
          projectId: fct-pp